### ISSUE TITLE
When changing versions fly is not redownloaded

### ISSUE THREAD

**Issue by baszalmstra** [ahelal/ansible-concourse#64] opened 2018-03-23 16:56 UTC
When changing `concourseci-version` from `3.6.0` to `3.9.2` fly is not redownloaded which causes an error when trying to use it in the role:

```
fly version (3.6.0) is out of sync with the target (3.9.2).
```

**Comment by ahelal** [comment] 2018-03-23 18:54
that is normal since fly is client side tool. 
You need to sync your cli by typing `fly -t <TARGET> sync` for more info  please refer to concourse documentation.

**Comment by baszalmstra** [comment] 2018-03-23 22:51
I understand that, its also states in the error message. The problem is not on the client though, its in the ansible task of updating teams. Deleting the fly executable from te concourse-web server fixes the issue. Manually calling sync on the server would also work but that requires manual intervention.

**Comment by ahelal** [comment] 2018-03-25 03:21
Can you please give some logs or someway to  reproduce the issue ?

**Comment by baszalmstra** [comment] 2018-03-26 08:10
This is the error message I get during `manage | team | Ensure teams that are present exists` when I downgrade from 3.9.2 to 3.6.0:
```
{"changed": true, "cmd": "yes | /opt/concourseci/bin/fly -t manage set-team -n team1  --basic-auth-username=user1 --basic-auth-password=password", "delta": "0:00:00.014575", "end": "2018-03-26 10:08:22.161946", "item": "team1", "msg": "non-zero return code", "rc": 1, "start": "2018-03-26 10:08:22.147371", "stderr": "fly version (3.9.2) is out of sync with the target (3.6.0). to sync up, run the following:\n\n    fly -t manage sync\n\ncowardly refusing to run due to significant version discrepancy", "stderr_lines": ["fly version (3.9.2) is out of sync with the target (3.6.0). to sync up, run the following:", "", "    fly -t manage sync", "", "cowardly refusing to run due to significant version discrepancy"], "stdout": "", "stdout_lines": []}
```

**Comment by ahelal** [comment] 2018-05-01 09:40
This should be resolved with the new release. Please reopen the issue if you are still facing some issues.

**Closed by ahelal** 2018-05-01 09:40 UTC
